CREATE TABLE [dbo].[Employees]
(
	[Id] UNIQUEIDENTIFIER NOT NULL PRIMARY KEY CLUSTERED ([Id] ASC), 
    [FullName] NVARCHAR(100) NOT NULL, 
    [PhoneNumber] NVARCHAR(15) NOT NULL, 
    [CreationDate] DATETIME NOT NULL
)
