CREATE TABLE [dbo].[Employees]
(
	[Id] UNIQUEIDENTIFIER NOT NULL, 
    [FullName] NVARCHAR(100) NOT NULL, 
    [PhoneNumber] NVARCHAR(15) NOT NULL, 
    [CreationDate] DATETIME NOT NULL,
    CONSTRAINT [PK_Employees] PRIMARY KEY CLUSTERED ([Id] ASC),

)
